In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import plotly.express as px
import seaborn as sns

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


/kaggle/input/disease-symptoms-and-patient-profile-dataset/Disease_symptom_and_patient_profile_dataset.csv


## Exploração dos dados

In [2]:
df = pd.read_csv("/kaggle/input/disease-symptoms-and-patient-profile-dataset/Disease_symptom_and_patient_profile_dataset.csv")

In [33]:
df

Disease Fever Cough Fatigue Difficulty Breathing  Age  Gender  \
0      Influenza   Yes    No     Yes                  Yes   19  Female   
1    Common Cold    No   Yes     Yes                   No   25  Female   
2         Eczema    No   Yes     Yes                   No   25  Female   
3         Asthma   Yes   Yes      No                  Yes   25    Male   
4         Asthma   Yes   Yes      No                  Yes   25    Male   
..           ...   ...   ...     ...                  ...  ...     ...   
344       Stroke   Yes    No     Yes                   No   80  Female   
345       Stroke   Yes    No     Yes                   No   85    Male   
346       Stroke   Yes    No     Yes                   No   85    Male   
347       Stroke   Yes    No     Yes                   No   90  Female   
348       Stroke   Yes    No     Yes                   No   90  Female   

    Blood Pressure Cholesterol Level Outcome Variable  
0              Low            Normal         Positive  
1           Normal            Normal         Negative  
2           Normal            Normal         Negative  
3           Normal            Normal         Positive  
4           Normal            Normal         Positive  
..             ...               ...              ...  
344           High              High         Positive  
345           High              High         Positive  
346           High              High         Positive  
347           High              High         Positive  
348           High              High         Positive  

[349 rows x 10 columns]

In [4]:
df['Disease'].nunique()

116

In [5]:
np.unique(df['Outcome Variable'], return_counts=True)

(array(['Negative', 'Positive'], dtype=object), array([163, 186]))

## Visualização dos dados

In [6]:
fig = px.histogram(data_frame=df, x='Age', color='Age')
fig.update_layout(showlegend=False)

fig.show()

In [7]:
Diseases_counts = df['Disease'].value_counts()

In [8]:
Diseases_counts

Asthma                            23
Stroke                            16
Osteoporosis                      14
Hypertension                      10
Diabetes                          10
                                  ..
Autism Spectrum Disorder (ASD)     1
Hypoglycemia                       1
Fibromyalgia                       1
Eating Disorders (Anorexia,...     1
Williams Syndrome                  1
Name: Disease, Length: 116, dtype: int64

In [9]:
Diseases_counts = Diseases_counts[Diseases_counts >= 4]

In [10]:
Diseases_counts.index

Index(['Asthma', 'Stroke', 'Osteoporosis', 'Hypertension', 'Diabetes',
       'Migraine', 'Influenza', 'Pneumonia', 'Bronchitis', 'Hyperthyroidism',
       'Hypothyroidism', 'Osteoarthritis', 'Kidney Cancer', 'Common Cold',
       'Liver Cancer', 'Depression', 'Rheumatoid Arthritis', 'Eczema',
       'Allergic Rhinitis', 'Anxiety Disorders', 'Gastroenteritis',
       'Urinary Tract Infection', 'Liver Disease', 'Psoriasis',
       'Alzheimer's Disease', 'Crohn's Disease', 'Multiple Sclerosis',
       'Coronary Artery Disease', 'Pancreatitis', 'Parkinson's Disease',
       'Ulcerative Colitis', 'Kidney Disease',
       'Chronic Obstructive Pulmonary Disease (COPD)'],
      dtype='object')

In [11]:
Diseases_counts.values

array([23, 16, 14, 10, 10, 10,  8,  8,  8,  7,  7,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  4])

In [12]:
px.pie(Diseases_counts, names=Diseases_counts.index, values=Diseases_counts.values)

## Divisão entre classe e previsor

In [13]:
X = df.drop('Outcome Variable', axis=1).values
y = df['Outcome Variable'].values

In [14]:
X.shape, y.shape

((349, 9), (349,))

## Pre-processamento

In [15]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [16]:
label = LabelEncoder()


X[:, 0] = label.fit_transform(X[:, 0])
X[:, 1] = label.fit_transform(X[:, 1])
X[:, 2] = label.fit_transform(X[:, 2])
X[:, 3] = label.fit_transform(X[:, 3])
X[:, 4] = label.fit_transform(X[:, 4])
X[:, 5] = label.fit_transform(X[:, 5])
X[:, 6] = label.fit_transform(X[:, 6])
X[:, 7] = label.fit_transform(X[:, 7])
X[:, 8] = label.fit_transform(X[:, 8])

In [17]:
scaler_x = StandardScaler()

X = scaler_x.fit_transform(X)     

In [18]:
X

array([[ 0.02030724,  0.99713876, -0.95790522, ..., -0.99144064,
         0.00882697,  1.1053115 ],
       [-0.94476192, -1.00286945,  1.04394462, ..., -0.99144064,
         1.03569737,  1.1053115 ],
       [-0.55270257, -1.00286945,  1.04394462, ..., -0.99144064,
         1.03569737,  1.1053115 ],
       ...,
       [ 1.37743575,  0.99713876, -0.95790522, ...,  1.00863325,
        -1.01804343, -1.00263229],
       [ 1.37743575,  0.99713876, -0.95790522, ..., -0.99144064,
        -1.01804343, -1.00263229],
       [ 1.37743575,  0.99713876, -0.95790522, ..., -0.99144064,
        -1.01804343, -1.00263229]])

In [19]:
y

array(['Positive', 'Negative', 'Negative', 'Positive', 'Positive',
       'Positive', 'Positive', 'Positive', 'Negative', 'Negative',
       'Positive', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Positive', 'Positive',
       'Positive', 'Positive', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Positive',
       'Positive', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Positive', 'Positive', 'Positive', 'Positive',
       'Positive', 'Positive', 'Positive', 'Positive', 'Positive',
       'Negative', 'Negative', 'Positive', 'Positive', 'Positive',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negative',
       'Negative', 'Negative', 'Negative', 'Negative', 'Negati

## Divisão treino-teste

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [22]:
X_train.shape, y_train.shape

((244, 9), (244,))

In [23]:
X_test.shape, y_test.shape

((105, 9), (105,))

## Criação do regressor

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
clf = RandomForestClassifier(criterion="gini", n_estimators=20, random_state=0)

In [26]:
clf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20, random_state=0)

In [27]:
clf.score(X_test, y_test)

0.8

In [34]:
X_test

array([[ 0.02030724,  0.99713876,  1.04394462,  0.66494267,  1.72218149,
        -1.88519226, -0.99144064,  1.03569737,  1.1053115 ],
       [-0.94476192,  0.99713876, -0.95790522,  0.66494267,  1.72218149,
        -1.23053346,  1.00863325, -1.01804343, -1.00263229],
       [ 1.64886145, -1.00286945,  1.04394462, -1.50388904, -0.58065889,
         0.73344296,  1.00863325,  1.03569737,  0.05133961],
       [ 0.02030724,  0.99713876,  1.04394462,  0.66494267, -0.58065889,
        -1.39419816,  1.00863325, -1.01804343,  1.1053115 ],
       [ 0.08062406,  0.99713876,  1.04394462,  0.66494267,  1.72218149,
         1.22443706, -0.99144064, -1.01804343, -1.00263229],
       [-0.13048482,  0.99713876, -0.95790522,  0.66494267, -0.58065889,
         0.07878415,  1.00863325,  1.03569737, -1.00263229],
       [ 0.1710993 ,  0.99713876,  1.04394462,  0.66494267, -0.58065889,
         0.07878415, -0.99144064,  1.03569737, -1.00263229],
       [-0.70349463,  0.99713876, -0.95790522, -1.50388904, -0

In [35]:
X_alt = [[ 0.02030724,  0.99713876,  1.04394462,  0.66494267,  1.72218149,
        -1.88519226, -0.99144064,  1.03569737,  1.1053115 ]]

In [36]:
clf.predict(X_alt)

array(['Positive'], dtype=object)